### ISSUE TITLE
variable_scope() got multiple values for keyword argument 'reuse'

### ISSUE THREAD

**Issue by ameicler** [Russell91/TensorBox#100]
Hi all,

With this installation:
- Mac OSX El Capitan 10.11.6
- Tensorflow 0.9
- Python 2.7 within Anaconda

I succeeded in compiling TensorBox, but when running command line `python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output` here is the error I receive:

Traceback (most recent call last):
  File "train.py", line 537, in <module>
    main()
  File "train.py", line 534, in main
    train(H, test_images=[])
  File "train.py", line 442, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 335, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 236, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, phase, reuse)
  File "train.py", line 123, in build_forward
    cnn, early_feat, _ = googlenet_load.model(x, H, phase, reuse)
  File "/Users/ameicler/Developer/ressources/tensorbox/utils/googlenet_load.py", line 11, in model
    reuse=reuse)
  File "/Users/ameicler/Developer/ressources/tensorbox/utils/inception_v1.py", line 285, in inception_v1
    reuse=reuse) as scope:
  File "/Users/ameicler/anaconda/lib/python2.7/contextlib.py", line 84, in helper
    return GeneratorContextManager(func(*args, **kwds))
TypeError: variable_scope() got multiple values for keyword argument 'reuse'

Any idea on what might be causing this error?

**Comment by Russell91** [comment]
You will most likely need to upgrade to 0.11.

**Comment by ameicler** [comment]
Hi Russel,

Thanks for your answer. It solved the issue but a new error has come up.

Closing this ticket and opening a new one : #102
