### ISSUE TITLE
How do we evaluate the model generated by train.py?

### ISSUE THREAD

**Issue by fabioprev** [Russell91/TensorBox#109]
I am trying to evaluate a trained model in my own data set. I was able to run the train.py code on my own data set but when I try to evaluate the model I get an error:

**fname:  output/mydataset_2016_11_04_12.38/save.ckpt-50.
saving:  output/mydataset_2016_11_04_12.38/save.ckpt-50.
Traceback (most recent call last):
  File "evaluate.py", line 110, in <module>
    main()
  File "evaluate.py", line 92, in main
    pred_annolist.save(pred_boxes)
  File "/home/fabio/Projects/TensorBox/utils/annolist/AnnotationLib.py", line 119, in save
    save(fname, self);
  File "/home/fabio/Projects/TensorBox/utils/annolist/AnnotationLib.py", line 896, in save
    assert(False);
AssertionError**

I think I am running the code with wrong parameters. I am currently using these ones:

**python evaluate.py --weights output/mydataset_2016_11_04_12.38/save.ckpt-50 --test_boxes output/mydataset_2016_11_04_11.06/ --logdir output**

Anyone has experienced a similar problem to mine? Any help?

Thanks,
  Fabio

**Comment by juergen3** [comment]
I'm having the same problem and would appreciate some help as well.
Thank you,
Juergen

**Comment by DodgerAkame** [comment]
Well, I post for a kind of push : 
I do have this problem, and I showed this to my teacher, actually trying to use former files to see what's wrong (surely with my files), how it should work, etc.
But for now, I have the same issues.

**Comment by lukemurray** [comment]
I had this same issue. I believe you need to give it a file with the list of images you want to test. e.g. `python evaluate.py --weights output/mydataset/save.ckpt-xxx --test_boxes my_test_files.json`
