### ISSUE TITLE
how to use inception_v1.ckpt

### ISSUE THREAD

**Issue by MisayaZ** [Russell91/TensorBox#122]
hi, I want to test the benchmark of ReInspect algorithm.I modify the hype_file ='./hypes/lstm_rezoom.json'
and saver.restore(sess, './data/inception_v1.ckpt') in evaluate.ipynb, however, I got the error:

WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x7f6369b35c50>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    saver.restore(sess, './data/inception_v1.ckpt')
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1345, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.NotFoundError: Tensor name "decoder/delta_ip_boxes4" not found in checkpoint files ./data/inception_v1.ckpt
	 [[Node: save/restore_slice_258 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_258/tensor_name, save/restore_slice_258/shape_and_slice)]]

Caused by op u'save/restore_slice_258', defined at:
  File "test.py", line 37, in <module>
    saver = tf.train.Saver()
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 986, in __init__
    self.build()
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1015, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 620, in build
    restore_sequentially, reshape)
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 357, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 270, in restore_op
    preferred_shard=preferred_shard))
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/io_ops.py", line 204, in _restore_slice
    preferred_shard, name=name)
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 359, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/bryan/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "decoder/delta_ip_boxes4" not found in checkpoint files ./data/inception_v1.ckpt
	 [[Node: save/restore_slice_258 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_258/tensor_name, save/restore_slice_258/shape_and_slice)]]

**Comment by MisayaZ** [comment]
_hahahahhah_

**Comment by MisayaZ** [comment]
**hahfafadf
dafadfadfaf
adfdafadfafaf**

**Comment by MisayaZ** [comment]
`adfadf
afafdafdadf`

**Comment by MisayaZ** [comment]
`afadfafafasf
afafafafaf
afafadfdfdfdfdfdfdfdfdfdfdfdfdfdf
afadddddddddddddd`

**Comment by Russell91** [comment]
You can't restore from those slim checkpoint files. You have to use the slim load code. Note that this is already the default - we finetune from the imagenet weights provided by Google's TFSlim. Hope that make sense.

**Comment by lukemurray** [comment]
@Russell91 I didn't really understand what you meant. But is it possible to use say the inception_resnet_v2 TFSlim checkpoint as a starting point?
