### ISSUE TITLE
AttributeError: 'module' object has no attribute 'threading'

### ISSUE THREAD

**Issue by developer-mayuan** [Russell91/TensorBox#126]
I installed the tensorflow (version 0.11) from source and when I tried to train your model, I got the following error:
```
➜  tensorbox git:(master) python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:01:00.0
Total memory: 11.90GiB
Free memory: 11.04GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    main()
  File "train.py", line 534, in main
    train(H, test_images=[])
  File "train.py", line 457, in train
    t = tf.train.threading.Thread(target=thread_loop,
AttributeError: 'module' object has no attribute 'threading'
```
Since form the Readme.md file, it says that the program is supported by the version 0.11, so I want to know how to fix this issue. Thanks.

**Comment by Russell91** [comment]
If you installed from source, please try from tensorflow.train import
threading, or something similar. Otherwise install from pip. Unfortunately
this problem is upstream, and I can't do much to fix it.
