### ISSUE TITLE
Session has been closed

### ISSUE THREAD

**Issue by gitmenonsandu** [Russell91/TensorBox#142]
My environment is Tensorflow r0.11, Linux 16.04

while running " python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output"

I am getting the following error

Traceback (most recent call last):
  File "train.py", line 537, in <module>
    main()
  File "train.py", line 534, in main
    train(H, test_images=[])
  File "train.py", line 473, in train
    init_fn(sess)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 581, in callback
    saver.restore(session, model_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1340, in restore
    if not file_io.get_matching_files(file_path):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 231, in get_matching_files
    compat.as_bytes(filename), status)]
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.NotFoundErrorException in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train.py", line 439, in thread_loop
    sess.run(enqueue_op[phase], feed_dict=make_feed(d))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
CancelledError: Session has been closed.
: /home/sandukuttan/tensorbox/data

**Comment by gitmenonsandu** [comment]
pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.NotFoundError: /home/sandukuttan/tensorbox/data

**Comment by gitmenonsandu** [comment]
This error is while executing 
**$ python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output**

I didn't download the data set. I created my own json file.

I editted the "**_**hypes/overfeat_rezoom.json**_**" to read my json file.

There is no directory /path/tensorbox/data.
Where is it trying to acces that path
