### ISSUE TITLE
Again the undefined symbol error

### ISSUE THREAD

**Issue by zelle-github** [Russell91/TensorBox#157]
I am getting the following error when running train.py:

`Traceback (most recent call last):
  File "train.py", line 538, in <module>
    main()
  File "train.py", line 535, in main
    train(H, test_images=[])
  File "train.py", line 443, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 336, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 244, in build_forward_backward
    hungarian_module = tf.load_op_library('utils/hungarian/hungarian.so')
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: utils/hungarian/hungarian.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev`

I know this issue was posted twice already, but the fixes there did not help me.

I am using Ubuntu 12.04, Cuda 8.0, Python 2.7 and Pip also uses Python 2.7

I followed the github installation tutorial. My code is up to date and make and make hungarian worked without any problem.

**Comment by Russell91** [comment]
This is a problem with runcython. Can you please read the readme at github.com/russell91/runcython and file an issue there with a simple reproducable example?

**Comment by chaochaow** [comment]
Hi there,

I got the same problem but I did not have Cuda installed. Is this the issue? I got the overfeat_rezoom config with no problem. 

 I noticed when I run "make hungarian" in util folder, it returned "make: Nothing to be done for 'hungarian'. However, I saw hungarian.so in the sub-folder.

**Comment by chaochaow** [comment]
It looks like adding -D_GLIBCXX_USE_CXX11_ABI=0 into the make file fixes the problem as stated in a previous thread. 

I had problems to build tensorflow from the latest source code but PIP installation seems working fine.

**Comment by zelle-github** [comment]
> It looks like adding -D_GLIBCXX_USE_CXX11_ABI=0 into the make file fixes the problem as stated in a previous thread.

Actually, this line of code is already in the make file:
[Makefile](https://github.com/Russell91/TensorBox/blob/master/utils/Makefile#L14)

But it still doesn't work for me.

**Comment by DodgerAkame** [comment]
I actually have the same issue (posted an issue, didn't notice this one) and the code is the most recent.

**Comment by CWallbridge** [comment]
I am also encountering this same issue.

Ubuntu 16.04
Tensorflow 0.12.1

**Comment by CWallbridge** [comment]
Also the line in the original makefile only runs that line if the operating system is Darwin. We are both running Ubuntu.

**Comment by Elliyos** [comment]
I had a similar issue but adding the "-D..." line didn't fix it for me, nor did making/remaking hungarian. Installing libgcc did the trick though.

**Comment by AdamWP** [comment]
Has anyone found a solution to this on Ubuntu?  I've tried Ubuntu 16.04 with TF 1.3 and 1.2.  I've also tried gcc-5, gcc-6, and gcc-7.  TF and tensorbox (with reinspect) both compile from sources.   "make && make hungarian" finishes without errors.  However when I try to run train.py I get

Traceback (most recent call last):
  File "train.py", line 560, in <module>
    main()
  File "train.py", line 557, in main
    train(H, test_images=[])
  File "train.py", line 453, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 343, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train.py", line 250, in build_forward_backward
    hungarian_module = tf.load_op_library('utils/hungarian/hungarian.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: utils/hungarian/hungarian.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

**Comment by pyupcgithub** [comment]
@AdamWP  have you solved this problem ?

**Comment by RomanSteinberg** [comment]
@AdamWP have you checked the existence of file 'utils/hungarian/hungarian.so'?

@zelle-github have you solved the problem? If yes, describe the solution, please, and close the issue.
