### ISSUE TITLE
tensorflow 0.10 does not work, throws error

### ISSUE THREAD

**Issue by atique81** [Russell91/TensorBox#164]
Hello,

does it only work for tensorflow 0.11? I tried to ran it on tensorflow 0.10 and got the following error.

Traceback (most recent call last):
  File "evaluate.py", line 105, in <module>
    main()
  File "evaluate.py", line 86, in main
    pred_annolist, true_annolist = get_results(args, H)
  File "evaluate.py", line 25, in get_results
    pred_boxes, pred_logits, pred_confidences, pred_confs_deltas, pred_boxes_deltas = build_forward(H, tf.expand_dims(x_in, 0), 'test', reuse=None)
  File "/home/atique/tensorbox/train.py", line 124, in build_forward
    cnn, early_feat, _ = googlenet_load.model(x, H, reuse)
  File "/home/atique/tensorbox/utils/googlenet_load.py", line 10, in model
    reuse=reuse)
  File "/home/atique/tensorbox/utils/inception_v1.py", line 285, in inception_v1
    reuse=reuse) as scope:
  File "/usr/lib/python2.7/contextlib.py", line 84, in helper
    return GeneratorContextManager(func(*args, **kwds))
TypeError: variable_scope() got multiple values for keyword argument 'reuse'

**Comment by Russell91** [comment]
Yea, we drop support for older versions as Google makes updates. It's rather unfortunate that Google introduces so many breaking changes every month, but what can you do.

**Comment by atique81** [comment]
Yeah...thats really unfortunate for me! The system I am working on does not give me sudo access, and has got only cuda-7.5. So, I am not able to install tensorflow .11 as it requires cuda-8.0.
