### ISSUE TITLE
Error in evaluate

### ISSUE THREAD

**Issue by ufohuang98** [Russell91/TensorBox#247]
Hi, I retain the data with  25k images(MPII person +brainwhash)
In training step,It seems to running well,
But it has so error when I ran the evaluate.py. 
※Batch_size: 8
would you please give me some advices?
-------------------------------------------MESSAGE------------------------------------------------------------
---command---
testuser@BDD-DL01-ubu1604-03://home/testuser/tensorbox2$ python evaluate.py --weights output2//mpii2_rezoom_2017_05_25_07.32/save.ckpt-20000 --test_boxes data/mpii2/eval_boxes1.json

---result---
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "evaluate.py", line 105, in <module>
    main()
  File "evaluate.py", line 86, in main
    pred_annolist, true_annolist = get_results(args, H)
  File "evaluate.py", line 25, in get_results
    pred_boxes, pred_logits, pred_confidences, pred_confs_deltas, pred_boxes_deltas = build_forward(H, tf.expand_dims(x_in, 0), 'test', reuse=None)
  File "/home/testuser/tensorbox2/train.py", line 158, in build_forward
    [H['batch_size'] * H['grid_width'] * H['grid_height'], H['later_feat_channels']])
  File "/home/testuser/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2630, in reshape
    name=name)
  File "/home/testuser/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/testuser/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2329, in create_op
    set_shapes_for_outputs(ret)
  File "/home/testuser/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/testuser/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1667, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/testuser/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/testuser/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Cannot reshape a tensor with 249600 elements to shape [2400,832] (1996800 elements) for 'Reshape' (op: 'Reshape') with input shapes: [1,15,20,832], [2].

**Comment by arun542** [comment]
@ufohuang98 yeah facing the same issue

**Comment by opalby** [comment]
please modify the batch_size in hype.json

**Comment by RomanSteinberg** [comment]
Close due to issue author do not respond
