### ISSUE TITLE
Error in Training OverFeat

### ISSUE THREAD

**Issue by DrewNF** [Russell91/TensorBox#25]
Hi|! I tried putting the N iteratoion number to 200 to see if everything works before wait so long for the full training and this is the error I get:

W tensorflow/core/kernels/queue_base.cc:292] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:292] _1_fifo_queue_1: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train.py", line 246, in MyLoop
    sess.run(enqueue_op[phase], feed_dict=make_feed(d))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_1_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1, _recv_Placeholder_0, _recv_Placeholder_1_0, _recv_Placeholder_2_0)]]
Caused by op u'fifo_queue_1_enqueue', defined at:
  File "train.py", line 359, in <module>
    main()
  File "train.py", line 356, in main
    train(H, test_images=[])
  File "train.py", line 238, in train
    enqueue_op[phase] = q[phase].enqueue((x_in, confs_in, boxes_in))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 219, in enqueue
    return gen_data_flow_ops._queue_enqueue(self._queue_ref, vals, name=scope)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 430, in _queue_enqueue
    name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 661, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train.py", line 246, in MyLoop
    sess.run(enqueue_op[phase], feed_dict=make_feed(d))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue, _recv_Placeholder_0, _recv_Placeholder_1_0, _recv_Placeholder_2_0)]]
Caused by op u'fifo_queue_enqueue', defined at:
  File "train.py", line 359, in <module>
    main()
  File "train.py", line 356, in main
    train(H, test_images=[])
  File "train.py", line 238, in train
    enqueue_op[phase] = q[phase].enqueue((x_in, confs_in, boxes_in))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 219, in enqueue
    return gen_data_flow_ops._queue_enqueue(self._queue_ref, vals, name=scope)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 430, in _queue_enqueue
    name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 661, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()

Any Solution?

**Comment by Russell91** [comment]
Hey, this is actually a known bug where train.py just crashes on successful
completion due to threading. Try running for 5k iterations and visualizing
with tensor board. If anyone wants to fix the crash as well, that would be
great.

**Comment by DrewNF** [comment]
$ python eval.py --run=./output1/default_2016_06_02_17.51/
2016-06-02 18:03:12,675 INFO Starting Evaluation
2016-06-02 18:03:13,870 INFO ./output1/default_2016_06_02_17.51/save.ckpt-100
2016-06-02 18:03:14,654 INFO Step 0: Duration 109.341 ms

Thanks so much for the fast response! I tried and I see it crates the files I need to evaluate.
Then when i run eval.py i get this error:
Traceback (most recent call last):
  File "eval.py", line 174, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "eval.py", line 166, in main
    run_eval(H,FLAGS.run, FLAGS.hypes, output_path)
  File "eval.py", line 96, in run_eval
    H["arch"]["image_width"]))
  File "/Users/Andrea/TensorBox/utils/train_utils.py", line 18, in rescale_boxes
    assert r.x1 < r.x2
AssertionError

Anyone as the same problem before?

**Comment by Russell91** [comment]
Please try out the ipython notebook for now. The eval.py script is not officially supported. The next release, which I happen to be working towards at the moment, will include a python evaluate.py script that should run immediately after train.py finishes.

**Comment by DrewNF** [comment]
excuse the many questions!
but sometimes running the ipython code notebook I get this error, sometimes not:

0
saving:  ./output/val_default.idl
$ ./utils/annolist/doRPC.py --minOverlap 0.200000 ./data/airplane/airplane_bb_file_list.idl ./output/val_default.idl
Minimum width: 0 height: 0
Asorting too large/ too small detections
minWidth: 0
minHeight: 0
maxWidth:  inf
maxHeight:  inf
#Annotations: 0
Setting up graphs ...
No annotation/detection pair found for: image/ILSVRC2012_val_00000631.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00001390.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00003960.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00004089.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00004984.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00006217.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00008292.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00009537.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00010597.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00011405.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00011510.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00012111.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00012263.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00012386.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00014425.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00015498.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00016995.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00018616.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00019179.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00019677.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00021747.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00022532.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00022975.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00023316.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00023781.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00023863.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00024108.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00024747.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00026189.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00026859.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00028019.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00030411.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00030531.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00032804.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00033441.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00033920.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00034342.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00035783.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00036394.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00037645.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00037801.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00039213.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00041927.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00044253.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00046862.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00046971.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00047290.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00047829.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00047902.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00048111.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00049097.png frame: -1
No annotation/detection pair found for: image/ILSVRC2012_val_00049575.png frame: -1
No annotation/detection pair found for: image/ILSVRC2013_val_00001592.png frame: -1
No annotation/detection pair found for: image/ILSVRC2013_val_00001866.png frame: -1
No annotation/detection pair found for: image/ILSVRC2013_val_00001978.png frame: -1
No annotation/detection pair found for: image/ILSVRC2013_val_00002818.png frame: -1
No annotation/detection pair found for: image/ILSVRC2013_val_00003059.png frame: -1
No annotation/detection pair found for: image/ILSVRC2013_val_00003149.png frame: -1
No annotation/detection pair found for: image/ILSVRC2013_val_00003866.png frame: -1
No annotation/detection pair found for: image/ILSVRC2013_val_00003916.png frame: -1
No annotation/detection pair found for: image/ILSVRC2013_val_00004313.png frame: -1
missingFrames:  61
Number of detections on annotated frames:  0
Sorting scores ...
Gradually decrease score ...
saving:
/Users/Andrea/TensorBox/output/rpc-val_default_overlap0.2.txt

$ ./utils/annolist/plotSimple.py /Users/Andrea/TensorBox/output/rpc-val_default_overlap0.2.txt --output output/results.png
/usr/local/lib/python2.7/site-packages/matplotlib/legend.py:633: UserWarning: Legend does not support 'TensorBox/output/rpc-val_default_overlap0.2.txt' instances.
A proxy artist may be used instead.
See: http://matplotlib.org/users/legend_guide.html#using-proxy-artist
  "#using-proxy-artist".format(orig_handle)

**Comment by jacobswanUpUp** [comment]
Hey Russel, this is a great project and work.
But I got the same bug DrewNF reported days ago, and I try the solution you provide but it doesn't seem to work here.

When set the iteration to be 5k , I still got the same problem.

Is it related to the queue management in Python? Why it works in 5k iteration that DrewNF succeed in running?

Step: 4930, lr: 0.001000, Train Loss: 0.09, Test Accuracy: 98.7%, Time/image (ms): 227.1
Step: 4940, lr: 0.001000, Train Loss: 0.19, Test Accuracy: 95.3%, Time/image (ms): 222.7
Step: 4950, lr: 0.001000, Train Loss: 0.11, Test Accuracy: 98.0%, Time/image (ms): 227.1
Step: 4960, lr: 0.001000, Train Loss: 0.20, Test Accuracy: 96.7%, Time/image (ms): 218.5
Step: 4970, lr: 0.001000, Train Loss: 0.21, Test Accuracy: 96.7%, Time/image (ms): 219.3
Step: 4980, lr: 0.001000, Train Loss: 0.12, Test Accuracy: 99.3%, Time/image (ms): 222.9
Step: 4990, lr: 0.001000, Train Loss: 0.06, Test Accuracy: 97.7%, Time/image (ms): 224.6
W tensorflow/core/kernels/queue_base.cc:292] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:292] _1_fifo_queue_1: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train.py", line 246, in MyLoop
    sess.run(enqueue_op[phase], feed_dict=make_feed(d))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue, _recv_Placeholder_0, _recv_Placeholder_1_0, _recv_Placeholder_2_0)]]
Caused by op u'fifo_queue_enqueue', defined at:
  File "train.py", line 359, in <module>
    main()
  File "train.py", line 356, in main
    train(H, test_images=[])
  File "train.py", line 238, in train
    enqueue_op[phase] = q[phase].enqueue((x_in, confs_in, boxes_in))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 219, in enqueue
    return gen_data_flow_ops._queue_enqueue(self._queue_ref, vals, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 430, in _queue_enqueue
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 661, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()


Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train.py", line 246, in MyLoop
    sess.run(enqueue_op[phase], feed_dict=make_feed(d))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
CancelledError: Enqueue operation was cancelled
	 [[Node: fifo_queue_1_enqueue = QueueEnqueue[Tcomponents=[DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](fifo_queue_1, _recv_Placeholder_0, _recv_Placeholder_1_0, _recv_Placeholder_2_0)]]
Caused by op u'fifo_queue_1_enqueue', defined at:
  File "train.py", line 359, in <module>
    main()
  File "train.py", line 356, in main
    train(H, test_images=[])
  File "train.py", line 238, in train
    enqueue_op[phase] = q[phase].enqueue((x_in, confs_in, boxes_in))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 219, in enqueue
    return gen_data_flow_ops._queue_enqueue(self._queue_ref, vals, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 430, in _queue_enqueue
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 661, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()



Any suggestion?

**Comment by jacobswanUpUp** [comment]
FYI, when running the code, I use the ssh to connect my server.
So i didn't use the 'Tensorboard'.
Is it possible that it bugs because i didn't use Tensorboard so it crash then?

**Comment by DrewNF** [comment]
Hik Jacob! as Russel told to me, this is a bug, but at the end the algorithm works and makes what it have to! :) 🎱

**Comment by jacobswanUpUp** [comment]
Thx a lot!

**Comment by Russell91** [comment]
Okay, this has been fixed!

**Comment by rm8630** [comment]
Hey Russell91,
I got the same error as DrewNF got before and I am stuck here:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train.py", line 439, in thread_loop
    for d in gen:
  File "/root/tensorbox/utils/train_utils.py", line 82, in load_data_gen
    for d in data:
  File "/root/tensorbox/utils/train_utils.py", line 51, in load_idl_tf
    anno = rescale_boxes(I.shape, anno, H["image_height"], H["image_width"])
  File "/root/tensorbox/utils/train_utils.py", line 18, in rescale_boxes
    assert r.x1 < r.x2
AssertionError


Is there any solution to this problem?

**Comment by gmrhub** [comment]
I guess this[http://andyljones.tumblr.com/post/133267887103/tensorflow-placeholder-queue-errors](url) fixes by not using with statement.
for e.g.
sess = tf.Session(config=config)
<all the code block>

sess.close()

also replace eval with eval(session=sess)
