### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by JerryLauzzz** [Russell91/TensorBox#258]
OS: Ubuntu 17.04
Python: python3.6 Anaconda

Traceback (most recent call last):
  File "./utils/annolist/doRPC.py", line 830, in <module>
    main()
  File "./utils/annolist/doRPC.py", line 664, in main
    annoIDL = parse(annoFile)
  File "/home/jerry/deep_learning/CPDR/TensorBox/utils/annolist/AnnotationLib.py", line 758, in parse
    annolist = parseJSON(filename)
  File "/home/jerry/deep_learning/CPDR/TensorBox/utils/annolist/AnnotationLib.py", line 719, in parseJSON
    jdoc = json.load(f)
  File "/home/jerry/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/jerry/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/jerry/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jerry/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

I guess this is because apostrophe is not allowed in json file.

**Comment by RomanSteinberg** [comment]
@JerryLauzzz this error is not about TensorBox. So, I close the issue.
