### ISSUE TITLE
"The file is not exist " error since 8/22 commit

### ISSUE THREAD

**Issue by epreble** [Russell91/TensorBox#267]
I downloaded the repo on 8/15, and have been training models on a specific set of data, which is working fine. A colleague downloaded the repo on 8/25 (after the merges made on 8/22), and when training the model on the exact same data, gets the following error that loops forever through all images. When my colleague copies my repo (from pre 8/22), it works fine, so there does appear to be something broken in the latest update.

Command being run:
python train.py --hypes hypes/overfeat_la_dmc.json --logdir /data/output

Error messages as follows:
<snip - thousands of missing file messages>
...
The file is not exist /data/LA_DMC_2/train/LA_DMC_RGB3band567.png
The file is not exist /data/LA_DMC_2/train/LA_DMC_RGB3band435.png
The file is not exist /data/LA_DMC_2/train/LA_DMC_RGB3band502.png
Traceback (most recent call last):
  File "train.py", line 560, in <module>
    main()
  File "train.py", line 557, in main
    train(H, test_images=[])
  File "train.py", line 466, in train
    d = gen.next()
  File "/notebooks/utils/train_utils.py", line 94, in load_data_gen
    for d in data:
  File "/notebooks/utils/train_utils.py", line 82, in load_idl_tf
    print("The file is not exist {}".format(anno.imageName))
KeyboardInterrupt
--------------------

**Comment by mrlzla** [comment]
Could you provide hypes file?
Or value of "train_idl" in hypes file at least

**Comment by mrlzla** [comment]
Yes, there is some bag related to dict key that is not exist and incorrect error message. Try to update to latest version.

**Comment by mrlzla** [comment]
#268
