### ISSUE TITLE
ImportError: No module named 'data_utils'

### ISSUE THREAD

**Issue by gustavkkk** [Russell91/TensorBox#269]
Hi,@Russell91, I encountered the above error when running your code.
//////////////////////////////////////////////////////////////////////////////////
runfile('J:/working/Detection/TensorBox/evaluate.py', wdir='J:/working/Detection/TensorBox')
Traceback (most recent call last):
  File "<ipython-input-1-9f0cd1f4bf7b>", line 1, in <module>
    runfile('J:/working/Detection/TensorBox/evaluate.py', wdir='J:/working/Detection/TensorBox')
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "J:/working/Detection/TensorBox/evaluate.py", line 8, in <module>
    from train import build_forward
  File "J:\working\Detection\TensorBox\train.py", line 29, in <module>
    from utils import train_utils, googlenet_load, tf_concat
  File "J:\working\Detection\TensorBox\utils\train_utils.py", line 10, in <module>
    from data_utils import (annotation_jitter, annotation_to_h5)
ImportError: No module named 'data_utils'
////////////////////////////////////////////////////////
I think now the code doesn't build successfully.
data_utils, AnnotationLib,PalLib contains building problem.
Could you help me solve this problem?
Thanks in advance

**Comment by RomanSteinberg** [comment]
@gustavkkk what version of TF, Python, OS do you use?

**Comment by gustavkkk** [comment]
I have been using TF1.3, python3.5,windows

**Comment by mrlzla** [comment]
Currently this repo is not supported on python3*

**Comment by RomanSteinberg** [comment]
@gustavkkk you need python2 and it skips those (;) dot-commas. I planned to remove them somewhen.

**Comment by gustavkkk** [comment]
@RomanSteinberg,@mrlzla  Thank you for your advice

**Comment by RomanSteinberg** [comment]
As far as I understand the issue is resolved and could be closed
