### ISSUE TITLE
Can't run lstm rezoom

### ISSUE THREAD

**Issue by djanksy** [Russell91/TensorBox#27]
When I run
```
python train.py --hypes hypes/lstm_rezoom.json --gpu 0 --logdir output
```

I get the following error:
```
Traceback (most recent call last):
  File "train.py", line 616, in <module>
    main()
  File "train.py", line 613, in main
    train(H, test_images=[])
  File "train.py", line 499, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 404, in build
    boxes_loss[phase]) = build_forward_backward(H, x, encoder_net, phase, boxes, flags)
  File "train.py", line 307, in build_forward_backward
    tf.user_ops.hungarian(pred_boxes, outer_boxes, outer_flags, H['solver']['hungarian_iou']))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_user_ops.py", line 58, in hungarian
    box_classes=box_classes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 358, in apply_op
    with g.as_default(), ops.name_scope(name) as scope:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2715, in name_scope
    elif name and name[-1] == "/":
TypeError: 'float' object has no attribute '__getitem__'
```

**Comment by djanksy** [comment]
Note: I am on version 0.8

**Comment by Russell91** [comment]
You will need to install tensorflow from source, following the directions under ReInspect Installation & Training in the readme to use the LSTM module.

**Comment by djanksy** [comment]
I reinstall reinspect from the sources but luck no go! if do `name = str(name)` then maybe works
