### ISSUE TITLE
problem regarding make hungarian

### ISSUE THREAD

**Issue by Prince-kapoor1991** [Russell91/TensorBox#272]
whenever I tried to do make hungarian for loss function, this occurs, kindly help:

I'm using tensorflow version, 1.3.0

cd hungarian && \
	TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())') && \
	if [ `uname` == Darwin ];\
	then g++-5 -std=c++11 -shared hungarian.cc -o hungarian.so -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -I $TF_INC -undefined dynamic_lookup;\
	else g++-5 -std=c++11 -shared hungarian.cc -o hungarian.so -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -I  $TF_INC; fi
/bin/bash: line 4: g++-5: command not found
make: *** [hungarian/hungarian.so] Error 127

**Comment by RomanSteinberg** [comment]
@Prince-kapoor1991 read the error message:
```
/bin/bash: line 4: g++-5: command not found
```
It has nothing common with tensorflow or tensorbox even.

**Comment by GTFiber** [comment]
Somewhat related - encountered an issue with the make, searched the error and ended up here, so just putting my resolution here.

Error readout:
cd hungarian && \
	TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())') && \
	if [ `uname` == Darwin ];\
	then g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I $TF_INC -undefined dynamic_lookup;\
	else g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I  $TF_INC; fi
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Imperssonator/anaconda/envs/py27/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/Imperssonator/anaconda/envs/py27/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/Imperssonator/anaconda/envs/py27/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/Users/Imperssonator/anaconda/envs/py27/lib/python2.7/site-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/Users/Imperssonator/anaconda/envs/py27/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/Users/Imperssonator/anaconda/envs/py27/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/Users/Imperssonator/anaconda/envs/py27/lib/python2.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB/\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
make: *** [all] Error 1


Resolution:
`brew uninstall protobuf`
