### ISSUE TITLE
MultiTreading: module threading has no attribute Thread

### ISSUE THREAD

**Issue by pawaskumarsingh** [Russell91/TensorBox#288]
here is the code:

import threading
import time

exitFlag = 0

class myThread (threading.Thread):
   def __init__(self, threadID, name, counter):
      threading.Thread.__init__(self)
      self.threadID = threadID
      self.name = name
      self.counter = counter
   def run(self):
      print ("Starting " + self.name)
      print_time(self.name, self.counter, 5)
      print ("Exiting " + self.name)

def print_time(threadName, delay, counter):
   while counter:
      if exitFlag:
         threadName.exit()
      time.sleep(delay)
      print ("%s: %s" % (threadName, time.ctime(time.time())))
      counter -= 1

thread1 = myThread(1, "Thread-1", 1)
thread2 = myThread(2, "Thread-2", 2)

thread1.start()
thread2.start()
thread1.join()
thread2.join()
print ("Exiting Main Thread")

and the error is here:

 File "threading.py", line 1, in <module>
    import threading
  File "/home/mit/threading.py", line 6, in <module>
    class myThread (threading.Thread):
AttributeError: module 'threading' has no attribute 'Thread'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 12, in <module>
    import subprocess, tempfile, os.path, re, pwd, grp, os, time
  File "/usr/lib/python3.5/subprocess.py", line 441, in <module>
    import threading
  File "/home/mit/threading.py", line 6, in <module>
    class myThread (threading.Thread):
AttributeError: module 'threading' has no attribute 'Thread'

Original exception was:
Traceback (most recent call last):
  File "threading.py", line 1, in <module>
    import threading
  File "/home/mit/threading.py", line 6, in <module>
    class myThread (threading.Thread):
AttributeError: module 'threading' has no attribute 'Thread'

**Comment by RomanSteinberg** [comment]
This is not a TensorBox issue. Please, report it in threading library repo.
