### ISSUE TITLE
Error while using --hypes hypes/lstm_mobilenet_rezoom.json

### ISSUE THREAD

**Issue by arunsank** [Russell91/TensorBox#291]
I ran into the following error when using lstm_mobilenet_rezoom.json to train my data. I am working on the below 

Ubuntu :16.04
Tensorflow : 1.5.0
Cuda : 9.0
Any help with regards to this would be really helpful

Loading Mobile net
Traceback (most recent call last):
  File "train_tens.py", line 560, in <module>
    main()
  File "train_tens.py", line 557, in main
    train(H, test_images=[])
  File "train_tens.py", line 453, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train_tens.py", line 343, in build
    boxes_loss[phase]) = build_forward_backward(H, x, phase, boxes, flags)
  File "train_tens.py", line 250, in build_forward_backward
    hungarian_module = tf.load_op_library('utils/hungarian/hungarian.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: utils/hungarian/hungarian.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Note**
My makefile under utils reads as below

SHELL := /bin/bash

.PHONY: all
all:
	pip install runcython
	makecython++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp"

hungarian: hungarian/hungarian.so

hungarian/hungarian.so:
	cd hungarian &&
	TF_INC=$$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())') &&
	g++ -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -shared hungarian.cc -o hungarian.so -fPIC -I $$TF_INC

**Comment by RomanSteinberg** [comment]
@arunsank this issue is duplicate #283
