### ISSUE TITLE
Running test.py for new images

### ISSUE THREAD

**Issue by nerdykamil** [Russell91/TensorBox#292]
After evaluating I wanted to test the model on new images so used test.py script from cmd as follows:

$ python test.py  --datadir data/test_dir/ --graphfile output/overfeat_rezoom_2018_03_22_11.45/save.ckpt-10000.meta --weights output/overfeat_rezoom_2018_03_22_11.45/save.ckpt-10000

and it gives output:
Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-03-22 14:54:33.538520: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-22 14:54:33.538769: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.392
pciBusID: 0000:01:00.0
totalMemory: 3.94GiB freeMemory: 3.70GiB
2018-03-22 14:54:33.538796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "test.py", line 126, in <module>
    pred_annolist = get_results(args, H, os.path.dirname(args.datadir))
  File "test.py", line 66, in get_results
    x_in = tf.get_collection('placeholders')[0]
IndexError: list index out of range

Any leads about why there are no placeholder values in model anymore? Thanks

**Comment by RomanSteinberg** [comment]
@nerdykamil have you figured it out? 

If not then answer the following questions, please.  
- Have you checked 'placeholders' collection during training?  
- Did you tried another way of getting input node?
