### ISSUE TITLE
ImportError: No module named rect

### ISSUE THREAD

**Issue by zhouyongxiu** [Russell91/TensorBox#298]
When I run the train.py, there is a error as:

WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from model import TensorBox
  File "/app/zyx/project/TensorBox/model.py", line 28, in <module>
    from utils import train_utils, googlenet_load, tf_concat
  File "/app/zyx/project/TensorBox/utils/train_utils.py", line 12, in <module>
    from rect import Rect
ImportError: No module named rect

Is there someone can help solver this error, thanks in advance.

**Comment by zhouyongxiu** [comment]
@PumayHui Thanks for your reply, I have solved this issue as your method.
