### ISSUE TITLE
Cannot use rescaled images in Overfeat

### ISSUE THREAD

**Issue by admcl** [Russell91/TensorBox#30]
It seems like TensorBox is meant to digest training images into a standard size that is set by the user.   In the configuration .json file, arch.image_width and arch.image_height imply this (as well as train.utils.load_idl_tf() which resizes all training images to the arch.* specifications).  However, I'm running into two issues:

1. In train_utils.load_idl_tf() lines 46-49 in the newest code (although I'm using code from a few months ago that doesn't appear to be different in this section) images of a different size than specified in the configuration file are resized with cv2.imresize(), which changes their aspect ratio.   I found that when  training TensorBox/Overfeat using the COCO image set, the results were horrible until I changed this code to preserve aspect ratio by first resizing the image by a scalar value and then padding the image if necessary to force the image size to 640x480.  After doing this, Overfeat began performing well on COCO data.

2.  I'm trying to make Tensorbox run as quickly as possible to reduce lag when giving Tensorbox input directly from a webcam.  I have my trained model running in much the same way that TensorBox sets up GoogleNet for training, except the FIFO queue has a length of 1 and polls from a webcam instead of the file system.   On a Macbook Pro with a Core i7 processor, I'm getting about 1Hz update rate, with about a 2-3s lag.  The lag in particular seems very poor, and I suspect it has to do with the 640x480 input layer.   It looks like I should be able to tweak TensorBox to accept a much smaller input image by changing the configuration file to something similar to this:

> "arch": {
        "use_lstm": false,
        "use_dropout": true, 
        "image_width": 160, 
        "image_height": 120,
        "grid_height": 15, 
        "grid_width": 20,
        "batch_size": 1, 
        "region_size": 8,
        "lstm_size": 200,
        "num_classes": 2,
        "rnn_len": 1
    }, 

...However, that produces the following error when trying to train the model:

> Traceback (most recent call last):
  File "train.py", line 360, in <module>
    main()
  File "train.py", line 357, in main
    train(H, test_images=[])
  File "train.py", line 251, in train
    smooth_op, global_step, learning_rate) = build(H, q)
  File "train.py", line 173, in build
    boxes_loss[phase]) = build_overfeat(H, x, googlenet, phase, boxes, confidences_r)
  File "train.py", line 114, in build_overfeat
    pred_boxes, pred_logits, pred_confidences = build_overfeat_forward(H, x, googlenet, phase)
  File "train.py", line 100, in build_overfeat_forward
    Z = googlenet_load.model(x, googlenet, H)
  File "/home/***/tensorbox/utils/googlenet_load.py", line 117, in model
    attrs =  op.node_def.attr
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2156, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1612, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/common_shapes.py", line 238, in conv2d_shape
    in_rows, in_cols, filter_rows, filter_cols, stride_r, stride_c, padding)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/common_shapes.py", line 151, in get2d_conv_output_size
    % (filter_height, filter_width, input_height, input_width))
ValueError: filter must not be larger than the input: Filter: [5x5] Input: [4x5]

Is TensorBox not designed to accept images that aren't 640x480, or is this a bug?   Is this the best way to go about reducing run time for the trained model, or is there another aspect of the model that might be changed?

**Comment by Russell91** [comment]
1) Interesting point about images performing better with padding than with rescaling. If you wanted to change the code to do the rescale with padding for anisotropic transformations, I'd welcome the pull request.

2) You can change the image height and width, but they both need to be multiples of 32, and you need to set grid_height = image_height / 32 and grid_width = image_width / 32

**Comment by avaranovich** [comment]
what if the resolution 320x240? 240/32 = 7.5 which is not accepted type (float). I can't round it, since there is an assertion     `assert H['region_size'] == H['image_width'] / H['grid_width']`
