### ISSUE TITLE
KeyError: u'Hungarian'

### ISSUE THREAD

**Issue by quanh1990** [Russell91/TensorBox#301]
I have successfully trained the model, but when I run evaluate.py I got this error 

Traceback (most recent call last):
  File "/opt/app/OCR/tensorbox/test.py", line 121, in <module>
    pred_annolist = get_results(args, H, os.path.dirname(args.datadir))
  File "/opt/app/OCR/tensorbox/test.py", line 50, in get_results
    new_saver = tf.train.import_meta_graph(args.graphfile)
  File "/root/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1927, in import_meta_graph
    **kwargs)
  File "/root/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 741, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/root/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 457, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/root/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 227, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: u'Hungarian'

**Comment by lonelylingoes** [comment]
I have the same problem. And I don't know how to resolve it.

**Comment by lonelylingoes** [comment]
I solve it, reference to https://github.com/tensorflow/tensorflow/issues/23369.

**Comment by RomanSteinberg** [comment]
@quanh1990 @lonelylingoes this the problem of loading model. You trained without "Hungarian" nodes in computation graph. But when you loaded the checkpoint you are trying to use such nodes.
