### ISSUE TITLE
what's wrong with this, my data set is too big?

### ISSUE THREAD

**Issue by Duum** [Russell91/TensorBox#31]
```
Traceback (most recent call last):
  File "train.py", line 620, in <module>
    main()
Cancelling data input queues

  File "train.py", line 617, in main
    Cancelling data input queues
train(H, test_images=[])

  File "train.py", line 555, in train
    ], feed_dict=lr_feed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shape[1,240,320,64]
	 [[Node: conv2d0_pre_relu/conv = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](sub, conv2d0_w/read)]]
	 [[Node: decoder_1/mul_4/_142 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_6368_decoder_1/mul_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'conv2d0_pre_relu/conv', defined at:
  File "train.py", line 620, in <module>
    main()
  File "train.py", line 617, in main
    train(H, test_images=[])
  File "train.py", line 500, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 405, in build
    boxes_loss[phase]) = build_forward_backward(H, x, encoder_net, phase, boxes, flags)
  File "train.py", line 300, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, googlenet, phase, reuse)
  File "train.py", line 197, in build_forward
    Z, early_feat, _ = googlenet_load.model(x, googlenet, H)
  File "/home/duum/tensorbox/utils/googlenet_load.py", line 118, in model
    attrs =  op.node_def.attr
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()

```
what's wrong with this, my data set is too big? and I have 600 images in train,  450 in test.and when i change them all to 100+ items it's work well.

**Comment by Russell91** [comment]
What gpu are you using?

**Comment by Duum** [comment]
GeForce GTX TITAN X
