### ISSUE TITLE
Module Import Error on Py3.5 / OSX-64

### ISSUE THREAD

**Issue by streblo** [Russell91/TensorBox#33]
I am trying to install TensorBox and get the following error:
```
$ python train.py --help
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    from utils import train_utils
  File "/.../tensorbox/utils/train_utils.py", line 10, in <module>
    from data_utils import (annotation_jitter, annotation_to_h5)
ImportError: No module named 'data_utils'
```
Although it seems like the module is there:
```
$ cd utils/
$ ls
Makefile		annolist		hungarian		stitch_rects.cpp	stitch_wrapper.pyx
__init__.py		data_utils.py		kaffe			stitch_rects.hpp	stitch_wrapper.so
__pycache__		googlenet_load.py	rect.py			stitch_wrapper.py	train_utils.py
$ grep 'annotation_jitter' data_utils.py 
def annotation_jitter(I, a_in, min_box_width=20, jitter_scale_min=0.9, jitter_scale_max=1.1, jitter_offset=16, target_width=640, target_height=480):
```

Perhaps OSX or Py3.5 isn't supported? I realize this may be operator error. Even so, I can submit a PR for updating the docs to prevent it in the future.

**Comment by streblo** [comment]
The problem stems from changes to `import` in python3, but I don't think python3 is supported by TensorBox.

http://stackoverflow.com/questions/12172791/changes-in-import-statement-python3
