### ISSUE TITLE
TypeError: List of Tensors when single Tensor expected in Tensorflow 0.7

### ISSUE THREAD

**Issue by violivei** [Russell91/TensorBox#48]
Hello,

First of all, sorry the newbie question, but I'm facing an issue when using TensorBox with its default training images.
This is my output:

```
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 860M
major: 5 minor: 0 memoryClockRate (GHz) 0.54
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.70GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:717] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 860M, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 2.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 4.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 8.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 16.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 32.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 64.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 128.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 256.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 512.0KiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 2.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 4.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 8.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 16.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 32.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 64.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 128.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 256.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 512.00MiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 2.00GiB
Traceback (most recent call last):
  File "train.py", line 532, in <module>
    main()
  File "train.py", line 529, in main
    train(H, test_images=[])
  File "train.py", line 442, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 397, in build
    tf.image_summary(phase + '/pred_boxes', pred_log_img)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/summary_ops.py", line 111, in image_summary
    tag=tag, tensor=tensor, max_images=max_images, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_summary_ops.py", line 91, in _image_summary
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 411, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 529, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 178, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/constant_op.py", line 161, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 319, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 256, in _AssertCompatible
    raise TypeError("List of Tensors when single Tensor expected")
TypeError: List of Tensors when single Tensor expected

```

Any ideas on what is going on here?

Thanks in advance.

**Comment by DrewNF** [comment]
It's due to a problem, I will give a look to it, for now you can comment the following lines and run the training:
tf.image_summary(phase + '/pred_boxes', pred_log_img)
tf.image_summary(phase + '/true_boxes', true_log_img)

**Comment by violivei** [comment]
Thanks! Please, keep us updated.
=)

**Comment by DrewNF** [comment]
I give a rapid look to the problem, you have to pack the tensor so add the tf.pack() function to the tf summary:
tf.image_summary(phase + '/pred_boxes', tf.pack(pred_log_img))
tf.image_summary(phase + '/true_boxes', tf.pack(true_log_img))
You could also use the max_images=10 arg of image_summary to limit as well the number of total images, I solved and made a pull request: #49 
You can solve the error in the meantime!

**Comment by violivei** [comment]
Did you receive this error message?

```
Traceback (most recent call last):
  File "train.py", line 532, in <module>
    main()
  File "train.py", line 529, in main
    train(H, test_images=[])
  File "train.py", line 464, in train
    writer.add_graph(sess.graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/summary_io.py", line 168, in add_graph
    graph_bytes = graph_def.SerializeToString()
AttributeError: 'Graph' object has no attribute 'SerializeToString'

```

**Comment by DrewNF** [comment]
I'm running the same code and works, the raised error is not from the code but from tensorflow, as suggested here: https://github.com/tensorflow/tensorflow/issues/1690 maybe you need to update or upgrade your tensorflow! :)

**Comment by violivei** [comment]
I have just updated. I was running with tensorflow 0.7.
Thanks anyways.

**Comment by Russell91** [comment]
Okay, this problem should be fixed via a try-except workaround [here](https://github.com/Russell91/TensorBox/commit/f42dad9588efb9353e27ae66b6cc303b354cd400). Please let me know if anyone is still getting this error.
