### ISSUE TITLE
Error in LSTM model on GPU

### ISSUE THREAD

**Issue by nitish11** [Russell91/TensorBox#59]
After setting up Tensorflow from source using [source](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#installing-from-sources)

OverFeat [Installation](https://github.com/Russell91/TensorBox#overfeat-installation--training) & Training is working fine. 
```
$ python train.py --hypes hypes/overfeat.json --gpu 0 --logdir output
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:118] Found device 0 with properties: 
name: GeForce GTX 750 Ti
major: 5 minor: 0 memoryClockRate (GHz) 1.15
pciBusID 0000:03:00.0
Total memory: 2.00GiB
Free memory: 1.93GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:138] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:148] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:868] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:03:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:868] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:03:00.0)
Step: 0, lr: 0.001000, Train Loss: 1.07, Test Accuracy: 54.0%, Time/image (ms): 0.0
Step: 50, lr: 0.001000, Train Loss: 0.96, Test Accuracy: 86.0%, Time/image (ms): 255.2
Step: 100, lr: 0.001000, Train Loss: 0.60, Test Accuracy: 90.3%, Time/image (ms): 171.4
Step: 150, lr: 0.001000, Train Loss: 0.92, Test Accuracy: 84.3%, Time/image (ms): 169.9
.
.
```
I am getting below error in Reinspect [model](https://github.com/Russell91/TensorBox#reinspect-installation--training). 
```
$ python train.py --hypes hypes/lstm_rezoom.json --gpu 0 --logdir output
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:118] Found device 0 with properties: 
name: GeForce GTX 750 Ti
major: 5 minor: 0 memoryClockRate (GHz) 1.15
pciBusID 0000:03:00.0
Total memory: 2.00GiB
Free memory: 1.93GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:138] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:148] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:868] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:03:00.0)
Traceback (most recent call last):
  File "train.py", line 533, in <module>
    main()
  File "train.py", line 530, in main
    train(H, test_images=[])
  File "train.py", line 443, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 336, in build
    boxes_loss[phase]) = build_forward_backward(H, x, encoder_net, phase, boxes, flags)
  File "train.py", line 235, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, googlenet, phase, reuse)
  File "train.py", line 157, in build_forward
    lstm_outputs = build_lstm_inner(H, lstm_input)
  File "train.py", line 39, in build_lstm_inner
    state = tf.zeros([batch_size, lstm.state_size])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1129, in zeros
    shape = ops.convert_to_tensor(shape, dtype=dtypes.int32, name="shape")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 628, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 180, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 354, in make_tensor_proto
    nparray = np.array(values, dtype=np_dt)
ValueError: setting an array element with a sequence.
```

**Comment by Russell91** [comment]
Please try to do at least a little debugging yourself. I'm not getting this
issue and the error appears to be in tf.zeros. Can you tell me what the
values of those arguments are?

**Comment by meetdave06** [comment]
Hi Russel , I am also getting a similar error.

The arguments for tf.zeros are as follows :- 

Batch_Size :-  300
LSTM  :-  (LSTMStateTuple(c=500, h=500), LSTMStateTuple(c=500, h=500))

**Comment by nitish11** [comment]
Hi @Russell91 : 

I checked it again, the parameters being passed are : 

```
Batch_Size 300
LSTM (LSTMStateTuple(c=500, h=500), LSTMStateTuple(c=500, h=500))
```

While debugging the code, the error is coming on [the line](https://github.com/Russell91/TensorBox/blob/master/train.py#L39)

Please check the below for detailed error log : 

```
type LSTM <type 'tuple'>
type LSTM (2, 2)
('!!!!!!!!!!!!!!!!!!!!!!!!', <tf.Tensor 'decoder/zeros:0' shape=(300, 2000) dtype=float32>)
Traceback (most recent call last):
  File "train.py", line 551, in <module>
    main()
  File "train.py", line 548, in main
    train(H, test_images=[])
  File "train.py", line 461, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 352, in build
    boxes_loss[phase]) = build_forward_backward(H, x, encoder_net, phase, boxes, flags)
  File "train.py", line 248, in build_forward_backward
    pred_confidences, pred_confs_deltas, pred_boxes_deltas) = build_forward(H, x, googlenet, phase, reuse)
  File "train.py", line 168, in build_forward
    lstm_outputs = build_lstm_inner(H, lstm_input)
  File "train.py", line 53, in build_lstm_inner
    output, state = lstm(lstm_input, state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn_cell.py", line 807, in __call__
    % (len(self.state_size), state))
ValueError: Expected state to be a tuple of length 2, but received: Tensor("decoder/zeros:0", shape=(300, 2000), dtype=float32)
```
Let me know how to debug the issue.

**Comment by meetdave06** [comment]
Hi Russell , Any updates ?

**Comment by piyushshri** [comment]
I encountered the same issue while running on single GPU machine (NVidia GeForce GTX 750 Ti). It works fine without GPU.
Can it be a problem because of state_is_tuple flag?

**Comment by huyong1109** [comment]
@piyushshri is right. The error is due to updates in TF. In LSTM, state is tuple default after 0.10.0.
Add "state_is_tuple=False" solves this problem. 
```
lstm_cell = rnn_cell.BasicLSTMCell(H['lstm_size'], forget_bias=0.0, state_is_tuple=False)
         if H['num_lstm_layers'] > 1:
           lstm = rnn_cell.MultiRNNCell([lstm_cell] * H['num_lstm_layers'], state_is_tuple=False)

```

**Comment by piyushshri** [comment]
Thanks @huyong1109 . Setting state_is_tuple to false started the training. However, this practice is no longer encouraged in TensorFlow and will be deprecated soon.

`WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x7f2f9b539810>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.`

@Russell91 Kindly note this issue. Is there a better approach to it?

**Comment by nitish11** [comment]
@piyushshri  : Yes, it's working now. 

As mentioned by @piyushshri , you need to following changes in train.py. Replace [these lines] (https://github.com/Russell91/TensorBox/blob/master/train.py#L32-L34) with code below.


```
   lstm_cell = rnn_cell.BasicLSTMCell(H['lstm_size'], forget_bias=0.0, state_is_tuple=False)
   if H['num_lstm_layers'] > 1:
       lstm = rnn_cell.MultiRNNCell([lstm_cell] * H['num_lstm_layers'], state_is_tuple=False)
```
