### ISSUE TITLE
Tensorflow error when training on hypes/lstm_rezoom.json

### ISSUE THREAD

**Issue by babylonico** [Russell91/TensorBox#60]
Hello,
I've installed CPU only Tensorflow 0.10 on an Ubuntu 15.10 machine. I'm running Python 2.7.10. I cloned tensorbox and all the makes ran smoothly for Overfeat and ReInspect. I can get `python train.py --hypes hypes/overfeat_rezoom.json` running just fine, however when I run `python train.py --hypes hypes/lstm_rezoom.json`, I get the following error:

Traceback (most recent call last):
  File "train.py", line 533, in <module>
    main()
  File "train.py", line 530, in main
    train(H, test_images=[])
  File "train.py", line 443, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 336, in build
    boxes_loss[phase]) = build_forward_backward(H, x, encoder_net, phase, boxes, flags)
  File "train.py", line 242, in build_forward_backward
    hungarian_module = tf.load_op_library('utils/hungarian/hungarian.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 75, in load_op_library
    raise errors._make_specific_exception(None, None, error_msg, error_code)
tensorflow.python.framework.errors.NotFoundError: utils/hungarian/hungarian.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

Haven't been able to find much information on this error. Given that the makes happened smoothly,  why might this be happening?

Thanks

**Comment by Russell91** [comment]
Can you check if your pip and python commands are using the same python
version?

**Comment by babylonico** [comment]
`pip -V` = `pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)`
and
`python -V` = `Python 2.7.10`

so I think yes

**Comment by swearos** [comment]
did you solve it?

**Comment by swearos** [comment]
OK,I solver it by modifying the Makefile under the folder of "utils",like this "g++ -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -shared hungarian.cc -o hungarian.so -fPIC -I $$TF_INC"
,because the GCC 5
[https://github.com/tensorflow/tensorflow/issues/1569](url)

**Comment by lukemurray** [comment]
I also got this error on Ubuntu 16.04 with Tensorflow 0.11.

Adding `-D_GLIBCXX_USE_CXX11_ABI=0` to the make file and rebuilding hungarian resolved it for me!

**Comment by brenda151295** [comment]
Hi @lukemurray I have this error:


https://github.com/Russell91/TensorBox/issues/146

and I tried that you said.
