### ISSUE TITLE
Error in Reading greyScale images

### ISSUE THREAD

**Issue by meetdave06** [Russell91/TensorBox#72]
While running training for Reinspect, I got error in reading  [greyscale images](https://github.com/Russell91/TensorBox/blob/master/utils/train_utils.py#L43)
```
python train.py --hypes hypes/lstm_rezoom.json --gpu 0 --logdir output
```
Image properties are as follows:
```
Image Name  /home/dave/DeepLearning/TensorBox/data/cars_train/08144.jpg
Image Shape  (683, 883)
```

The error trace is as follows:
````
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "train.py", line 439, in thread_loop
    for d in gen:
  File "/home/dave/DeepLearning/TensorBox/utils/train_utils.py", line 83, in load_data_gen
    for d in data:
  File "/home/dave/DeepLearning/TensorBox/utils/train_utils.py", line 48, in load_idl_tf
    if I.shape[2] == 4:
IndexError: tuple index out of range
```

**Comment by meetdave06** [comment]
You can skip the greyscale training images by adding following [lines](https://github.com/Russell91/TensorBox/blob/b6754d60852808f0d943c549ec03401851855565/utils/train_utils.py#L44-L46)

Check [PR] (https://github.com/Russell91/TensorBox/tree/b6754d60852808f0d943c549ec03401851855565) with updated lines.
