### ISSUE TITLE
an error occours when do train 

### ISSUE THREAD

**Issue by 6676401088** [Russell91/TensorBox#89]
binbin@binbin:~/git-projects/TensorBox$ python train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output
Traceback (most recent call last):
  File "train.py", line 533, in <module>
    main()
  File "train.py", line 530, in main
    train(H, test_images=[])
  File "train.py", line 443, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 312, in build
    encoder_net = googlenet_load.init(H, config)
  File "/home/binbin/git-projects/TensorBox/utils/googlenet_load.py", line 26, in init
    graph_def.MergeFromString(f.read())
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1091, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1127, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/decoder.py", line 610, in DecodeRepeatedField
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

What does this error means? Can you give me some help?

**Comment by Russell91** [comment]
What version of tensorflow are you using?
