### ISSUE TITLE
googlenet_load.py - problem decode during train.py - python 3.5

### ISSUE THREAD

**Issue by decombas** [Russell91/TensorBox#93]
I am trying to use the train.py function and I have this problem : 

python train.py --hypes hypes/lstm_rezoom.json --gpu 0 --logdir output
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "train.py", line 533, in <module>
    main()
  File "train.py", line 530, in main
    train(H, test_images=[])
  File "train.py", line 443, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 312, in build
    encoder_net = googlenet_load.init(H, config)
  File "/media/watiz/DATA/travail/Code/tensorbox/utils/googlenet_load.py", line 30, in init
    graph_def.MergeFromString(f.read())
  File "/home/watiz/.virtualenvs/cv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 100: invalid start byte

I have tried to modify in googlenet_load.py 
 with open(graph_def_orig_file) as f:  by with open(graph_def_orig_file,'r',-1,'UTF-8','replace') as f:

and I have :
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:116] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1109, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 533, in <module>
    main()
  File "train.py", line 530, in main
    train(H, test_images=[])
  File "train.py", line 443, in train
    smooth_op, global_step, learning_rate, encoder_net) = build(H, q)
  File "train.py", line 312, in build
    encoder_net = googlenet_load.init(H, config)
  File "/media/watiz/DATA/travail/Code/tensorbox/utils/googlenet_load.py", line 30, in init
    graph_def.MergeFromString(f.read())
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1093, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

Do you have any suggestions to solve the problem ?

**Comment by Russell91** [comment]
What version of tensorflow are you using?

**Comment by decombas** [comment]
I am using the tensorflow version '0.11.0rc0'

**Comment by Russell91** [comment]
Please install 0.10. I updated the README to give this advice. The Google
guys make breaking changes on literally every release. Getting quite
annoying...

**Comment by decombas** [comment]
Ok, I will do that. if you have any suggestions to try to find a solution or where I can search to solve the problem, can you let me know ?

**Comment by Russell91** [comment]
Well, the readme instructions should absolutely let people get things up
and running. So please post updates if you can't get 0.10 working.

**Comment by decombas** [comment]
Ok, I will test with 0.10
